services:
  # PostgreSQL Database
  - type: pserv
    name: pastoral-database
    plan: free
    ipAllowList: []

  # Redis Service
  - type: redis
    name: pastoral-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Backend Service
  - type: web
    name: pastoral-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pastoral-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: pastoral-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: pastoral-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: PORT
        value: 80
      - key: BACKEND_URL
        value: https://pastoral-backend.onrender.com
    autoDeploy: true
