"""Add name normalization fields and review queue

Revision ID: ce9b3a1a9571
Revises: f0b05a9d2a87
Create Date: 2025-09-16 13:29:29.391846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9b3a1a9571'
down_revision = 'f0b05a9d2a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('left_context', sa.String(length=400), nullable=False),
    sa.Column('right_context', sa.String(length=400), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['registrants.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_review_queue_created_at'), 'name_review_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_name_review_queue_id'), 'name_review_queue', ['id'], unique=False)
    op.add_column('registrants', sa.Column('raw_full_name', sa.String(length=200), nullable=True))
    op.add_column('registrants', sa.Column('normalized_full_name', sa.String(length=200), nullable=True))
    op.add_column('registrants', sa.Column('canonical_full_name', sa.String(length=200), nullable=True))
    op.add_column('registrants', sa.Column('audience', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_registrants_audience'), 'registrants', ['audience'], unique=False)
    op.create_index(op.f('ix_registrants_canonical_full_name'), 'registrants', ['canonical_full_name'], unique=False)
    op.create_index(op.f('ix_registrants_normalized_full_name'), 'registrants', ['normalized_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrants_normalized_full_name'), table_name='registrants')
    op.drop_index(op.f('ix_registrants_canonical_full_name'), table_name='registrants')
    op.drop_index(op.f('ix_registrants_audience'), table_name='registrants')
    op.drop_column('registrants', 'audience')
    op.drop_column('registrants', 'canonical_full_name')
    op.drop_column('registrants', 'normalized_full_name')
    op.drop_column('registrants', 'raw_full_name')
    op.drop_index(op.f('ix_name_review_queue_id'), table_name='name_review_queue')
    op.drop_index(op.f('ix_name_review_queue_created_at'), table_name='name_review_queue')
    op.drop_table('name_review_queue')
    # ### end Alembic commands ###