"""add_audience_to_catalog_career

Revision ID: 82e82d6d4152
Revises: ce9b3a1a9571
Create Date: 2025-10-18 14:49:09.179830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e82d6d4152'
down_revision = 'ce9b3a1a9571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_careers', sa.Column('audience', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_careers', 'audience')
    # ### end Alembic commands ###